name: scan_qr_member
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  awesome_dialog: ^3.3.0
  barcode_scan2: ^4.5.2
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  geolocator: ^14.0.2
  google_fonts: ^6.3.3
  http: ^1.6.0
  intl: ^0.20.2
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
